GET http://localhost:3010/api/wanaka/player/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3ODczMjg1MDUsInN1YiI6IjkyNTI1ODQwIn0.i5oFD4av6Me_jV8IZjDKfNOaBlxkv4nk4IhkBFTDN-A
