GET http://localhost:3010/api/wanaka/player HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJleHAiOjE3OTE1MzIxMTksInN1YiI6IjkyNTI1ODQwIn0.VTxG9VorA9iZgYYI9u0sv83dyrmlbfNXEFQh8etleVI